### ISSUE TITLE
Add support for parallel voice processing

### ISSUE THREAD

**Issue by kagu** [kunquat/kunquat#559]
Perhaps the most straightforward way to add support for parallelism is to divide the work on each voice group across several threads. This is also a good opportunity to move the remaining signal processing code from the init module to the player module where they belong. The current single-threaded processing mode should probably remain as the default of libkunquat, but it may be better to have the tracker use parallel voice processing by default.

**Comment by cyberixae** [comment]
Are you planning to have the same amount of threads and voices or is one thread going to be (re)used for several voices?

**Comment by cyberixae** [comment]
https://en.wikipedia.org/wiki/Thread_pool

**Comment by kagu** [comment]
I am planning to have a fixed (but user-configurable) amount of threads, so one thread will typically process several voice groups. (A voice group is a collection of voices that work together to produce a sound of one audible note.)
