### ISSUE TITLE
Python3 needs to be added to dependencies

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#575]
I'm not 100% sure but I think python3 is not part of a standard Ubuntu install. Perhaps it should be part of the installation instructions. Although maybe it will soon be part of a standard installation. Not sure how to check this without doing a fresh Ubuntu installation.

**Comment by cyberixae** [comment]
Maybe I was wrong ubuntu-minimal for Ubuntu 16.10 seems to depend on Python3 http://packages.ubuntu.com/yakkety/ubuntu-minimal

**Comment by cyberixae** [comment]
On the other hand adding the dependency would be an easy fix for people running an old version of Ubuntu.

**Comment by cyberixae** [comment]
I actually did follow the instructions and I ran into the problem of not having python3. Maybe it doesn't depend on python3?

**Comment by kagu** [comment]
That's interesting. Well, it doesn't hurt to add the python3 package explicitly.
