### ISSUE TITLE
Compiling fails with errors

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#576]
[cpuinfo.txt](https://github.com/kunquat/kunquat/files/664997/cpuinfo.txt)
[lsb-release.txt](https://github.com/kunquat/kunquat/files/664996/lsb-release.txt)
[uname.txt](https://github.com/kunquat/kunquat/files/664998/uname.txt)
[compile-log.txt](https://github.com/kunquat/kunquat/files/664999/compile-log.txt)
[compile-errors.txt](https://github.com/kunquat/kunquat/files/665000/compile-errors.txt)

**Comment by cyberixae** [comment]
I dropped the -Werror flag so I could get multiple erros logged at once

**Comment by cyberixae** [comment]
I was compiling Kunquat on my Samsung Series 3 Chromebook. I used Crouton to run Ubuntu on it.

**Comment by cyberixae** [comment]
I wonder if this is because of Ubuntu 12.04 or because of the arm processor. I guess we have compiled Kunquat on Ubuntu 12.04 at least once at some stage, but never on arm.

**Comment by kagu** [comment]
It seems that older versions of gcc have a broken implementation of the -Wshadow warning flag. I added the flag quite recently which is why we haven't encountered this problem before. Maybe we could check the gcc version and disable the warning if it causes problems.
The other warnings seem just weird to me, as I can't find any sign- or type-related issues at the code locations referenced. It might also be buggy behaviour in older versions of gcc.

**Comment by cyberixae** [comment]
[gcc-version-y.txt](https://github.com/kunquat/kunquat/files/667565/gcc-version-y.txt)
[cpuinfo-y.txt](https://github.com/kunquat/kunquat/files/667566/cpuinfo-y.txt)
[lsb-release-y.txt](https://github.com/kunquat/kunquat/files/667567/lsb-release-y.txt)
[uname-y.txt](https://github.com/kunquat/kunquat/files/667568/uname-y.txt)
[compiling-log-y.txt](https://github.com/kunquat/kunquat/files/667569/compiling-log-y.txt)

**Comment by cyberixae** [comment]
I installed Ubuntu 16.10. See the files *-y.txt above. There is still one warning left that prevents compilation.

```
src/lib/Handle_player.c: In function 'kqt_Handle_set_audio_rate':
src/lib/Handle_player.c:90:28: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     else if ((int64_t)rate > INT32_MAX)
                            ^
```

**Comment by cyberixae** [comment]
If I ignore the warning and proceed with installation everything seems to go fine, until I run the tracker. Then I get the following error.
[tracker-log-y.txt](https://github.com/kunquat/kunquat/files/667611/tracker-log-y.txt)

**Comment by cyberixae** [comment]
The tracker problem could of course be a different one.

**Comment by cyberixae** [comment]
I filed a separate issued for the JSON file loading problem #579

**Comment by cyberixae** [comment]
I also filed a separate issue for the memfd error. See #580

**Comment by cyberixae** [comment]
And finally, I also filed a separate issue for the compilation time warning for a problematic comparison. See #581

**Comment by cyberixae** [comment]
We should probably close this issue now since all described problems now have their own issue number. The initial logs contained some other problems as well but those seemed to only be relevant when compiling kunquat on old versions of GCC. People can perhaps compile kunquat on old versions of GCC by disabling some warnings but it probably does not make sense for the project to support old compilers.

**Comment by cyberixae** [comment]
I'm closing this now. We can always reopen it later if I forgot something.
