### ISSUE TITLE
shared memfd open() failed: Function not implemented

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#580]
When I start kunquat-tracker I get the following error `shared memfd open() failed: Function not implemented`

**Comment by kagu** [comment]
It looks like some part of the underlying system depends on a fairly recent version of Linux (memfd was added in version 3.17). I'm not sure which part needs it, though. Is this something that prevents the tracker from running? Does this also affect kunquat-player and/or kunquat-export?

**Comment by cyberixae** [comment]
I was able to play some notes regardless of the error. I did not check other functionalities.

**Comment by cyberixae** [comment]
If it doesn't cause any real trouble we might just keep this issue open for tracking the situation. Perhaps it is a harmless warning that will go away with time.

**Comment by cyberixae** [comment]
This warning is also printed when playing a module with kunquat-player.

**Comment by cyberixae** [comment]
However, this warning is NOT printed when rendering a module with kunquat-export.

**Comment by kagu** [comment]
Ok, my guess is that the warning comes from PulseAudio, at least if you have version 10 or later installed. It's probably safe to ignore the warning if audio playback is working correctly.

**Comment by kagu** [comment]
I am assuming that this warning does not occur with relatively recent versions of Linux, so I am closing the issue.
