### ISSUE TITLE
Include version information in stored JSON data

### ISSUE THREAD

**Issue by kagu** [kunquat/kunquat#774]
All stored Kunquat data in JSON format needs version information to help with maintaining backwards compatibility. The current format suggestion for all JSON data is to use a list of two elements: the first one is an integer version number and the second one is the payload.

Additionally, we might want to store the used tracker version string in a metadata field for improved diagnostics when the user attempts to load a module made with a more recent tracker version than the one installed.

**Comment by kagu** [comment]
My reason for preferring lists is that it's easier to parse on the libkunquat side, as it would guarantee that the version number always comes first. Using objects would require an additional pass just to retrieve the version number.

**Comment by cyberixae** [comment]
Typically JSON parsers would not have a streaming API. I would imagine that implementing a JSON parsers without streaming support would be easier than implementing a JSON parser with streaming support.

**Comment by cyberixae** [comment]
Although I guess you could just parse a bit from the beginning to get the version number. In this case parsing
```
[123, {broken JSON
```
would return version number 123.

**Comment by cyberixae** [comment]
I guess there is nothing wrong with that but the result would mean "It is version 123 or it might be invalid". Which means that you have to worry about validity everywhere. Knowing that "This is a valid file version 123" might be nice since you could then stop worrying about the files validity at that point.

**Comment by kagu** [comment]
Well, the parser inside libkunquat is not a typical JSON parser (in fact, it isn't really a JSON parser at all; it only accepts a set of quite strictly formatted data that also happens to be valid JSON). :-) I am not too concerned about making things human-readable on this level, and it seems like the list-based solution only requires a few additions to the existing codebase.

**Comment by cyberixae** [comment]
To be clear. I was thinking about code readability. For example lets consider
```
version = JSON.parse(data).version
```
and
```
version = JSON.parse(data)[0]
```
The first one looks correct. The second one could be correct or it could be broken.

**Comment by cyberixae** [comment]
Perhaps you could explain in the specification how this works? Anyone could then check the specification to see if
```
version = JSON.parse(data)[0]
```
is correct or not.

**Comment by kagu** [comment]
Sure, this needs to be in the specification.
