### ISSUE TITLE
PulseAudio initialisation fails on High Sierra

### ISSUE THREAD

**Issue by kagu** [kunquat/kunquat#818]

**Comment by cyberixae** [comment]
Do you know whether or not this is a bug in Kunquat? Is it possible that PulseAudio was incorrectly installed? Is it possible that the user needs to run some daemon for initialisation to work? It is of course good to document such things. I'm just wondering if this is a bug in software or could it be that PulseAudio is just tricky to setup on a Mac.

**Comment by kagu** [comment]
I investigated further, and this turned out to be a user error on my part.

**Comment by cyberixae** [comment]
Sometimes issues filed because of user errors are really valuable. For example it might be possible to improve error messages or documentation.
