### ISSUE TITLE
handle KunquatFormatError when calling validate

### ISSUE THREAD

**Issue by cyberixae** [kunquat/kunquat#99]
We need to report a bug to the user when the data inserted into kunquat does not validate. We also need to make sure that the invalid data is not saved to the disk. We may wish to create a backup of the previous consistent state whenever an error is encountered.

**Comment by kagu** [comment]
I believe the first two parts of this issue are covered by the existing codebase, and I have created a separate issue #842 for backup creation. So I'm closing this issue now.
